/**
 * 将 Vibeboard handoff tokens 转为 Design Tokens Community Group (DTCG) 草案格式
 */

export type HandoffTokensLike = {
  color?: string[];
  fontSize?: number[];
  radius?: number[];
  moodKeywords?: string[];
  visualStyle?: string | null;
};

/** DTCG-ish JSON（$value / $type）便于 Token Studio / Style Dictionary 消费 */
export function toDtcgTokens(tokens: HandoffTokensLike): Record<string, unknown> {
  const color: Record<string, unknown> = {};
  (tokens.color ?? []).forEach((value, i) => {
    color[`color-${i + 1}`] = {
      $type: "color",
      $value: value,
    };
  });

  const fontSize: Record<string, unknown> = {};
  (tokens.fontSize ?? []).forEach((value, i) => {
    fontSize[`size-${i + 1}`] = {
      $type: "dimension",
      $value: `${value}px`,
    };
  });

  const radius: Record<string, unknown> = {};
  (tokens.radius ?? []).forEach((value, i) => {
    radius[`radius-${i + 1}`] = {
      $type: "dimension",
      $value: `${value}px`,
    };
  });

  return {
    $description:
      "Generated by Vibeboard handoff. DTCG-compatible subset.",
    meta: {
      visualStyle: tokens.visualStyle ?? null,
      moodKeywords: tokens.moodKeywords ?? [],
    },
    color,
    fontSize,
    radius,
  };
}
