/**
 * tokens.json → 可直接 import 的代码产物
 * --------------------------------------------------------------
 *   design/tokens.css            :root 里的 CSS 自定义属性（Tailwind v4 可整段搬进 @theme）
 *   design/tailwind.tokens.cjs   Tailwind v3 `theme.extend` 片段（require 进 tailwind.config）
 * 色板有语义名时用语义名（--color-background / colors.background），否则 color-N。
 * 这样 coding agent 不用再手抄 hex。
 */

import type { HandoffTokensLike } from "./tokens-dtcg";

interface NamedColor {
  key: string;
  value: string;
  comment?: string;
}

export function renderTokensCss(tokens: HandoffTokensLike): string {
  const colors = namedColors(tokens);
  const lines: string[] = [
    "/* Generated by Vibeboard handoff — design tokens as CSS custom properties.",
    " * Colors marked `pixels` were sampled from the approved mockup; treat them as exact.",
    " * Tailwind v4: paste the declarations into `@theme { … }` (rename --color-* as you like).",
    " */",
    ":root {",
  ];
  for (const c of colors) {
    lines.push(`  --color-${c.key}: ${c.value};${c.comment ? ` /* ${c.comment} */` : ""}`);
  }
  (tokens.fontSize ?? []).forEach((px, i) => {
    lines.push(`  --font-size-${i + 1}: ${px}px;`);
  });
  (tokens.radius ?? []).forEach((px, i) => {
    lines.push(`  --radius-${i + 1}: ${px}px;`);
  });
  lines.push("}", "");
  return lines.join("\n");
}

export function renderTailwindTokens(tokens: HandoffTokensLike): string {
  const colors = namedColors(tokens);
  const colorEntries = colors.map(
    (c) => `      "${c.key}": "${c.value}",${c.comment ? ` // ${c.comment}` : ""}`,
  );
  const fontEntries = (tokens.fontSize ?? []).map((px, i) => `      "${i + 1}": "${px}px",`);
  const radiusEntries = (tokens.radius ?? []).map((px, i) => `      "${i + 1}": "${px}px",`);
  return [
    "// Generated by Vibeboard handoff — Tailwind v3 theme fragment.",
    "// tailwind.config.js:  const vb = require('./design/vibeboard/design/tailwind.tokens.cjs');",
    "//                      module.exports = { theme: { extend: { ...vb.theme.extend } } }",
    "// Tailwind v4: use design/tokens.css inside @theme instead.",
    "module.exports = {",
    "  theme: {",
    "    extend: {",
    "      colors: {",
    ...colorEntries.map((l) => `  ${l}`),
    "      },",
    "      fontSize: {",
    ...fontEntries.map((l) => `  ${l}`),
    "      },",
    "      borderRadius: {",
    ...radiusEntries.map((l) => `  ${l}`),
    "      },",
    "    },",
    "  },",
    "};",
    "",
  ].join("\n");
}

function namedColors(tokens: HandoffTokensLike): NamedColor[] {
  const out: NamedColor[] = [];
  const seen = new Set<string>();
  if (tokens.palette?.length) {
    for (const p of tokens.palette) {
      let key = toKey(p.name);
      let n = 2;
      while (seen.has(key)) key = `${toKey(p.name)}-${n++}`;
      seen.add(key);
      out.push({
        key,
        value: p.value,
        comment:
          [p.source, typeof p.share === "number" ? `${Math.round(p.share * 100)}%` : ""]
            .filter(Boolean)
            .join(" · ") || undefined,
      });
    }
    return out;
  }
  (tokens.color ?? []).forEach((value, i) => {
    out.push({ key: `color-${i + 1}`, value });
  });
  return out;
}

/** `accent@asset-01` → `accent-asset-01`；空名回退 color */
function toKey(name: string): string {
  const k = name
    .toLowerCase()
    .replace(/[@_\s]+/g, "-")
    .replace(/[^a-z0-9-]+/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return k || "color";
}
