import { describe, expect, it } from "vitest";
import { renderTailwindTokens, renderTokensCss } from "./tokens-export";

const tokens = {
  color: ["#181820", "#F0F0F5", "#7C3AED"],
  palette: [
    { name: "background", value: "#181820", source: "pixels", share: 0.82 },
    { name: "ink", value: "#F0F0F5", source: "pixels", share: 0.09 },
    { name: "accent@asset 01", value: "#7C3AED", source: "vision" },
    { name: "accent@asset 01", value: "#6D28D9", source: "prompt" },
  ],
  fontSize: [14, 32],
  radius: [8, 16],
};

describe("renderTokensCss", () => {
  it("emits semantic custom properties with provenance comments", () => {
    const css = renderTokensCss(tokens);
    expect(css).toContain(":root {");
    expect(css).toContain("--color-background: #181820; /* pixels · 82% */");
    expect(css).toContain("--color-ink: #F0F0F5; /* pixels · 9% */");
    expect(css).toContain("--color-accent-asset-01: #7C3AED; /* vision */");
    // 重名去重
    expect(css).toContain("--color-accent-asset-01-2: #6D28D9; /* prompt */");
    expect(css).toContain("--font-size-2: 32px;");
    expect(css).toContain("--radius-1: 8px;");
  });

  it("falls back to color-N without a named palette", () => {
    const css = renderTokensCss({ color: ["#111111"], fontSize: [], radius: [] });
    expect(css).toContain("--color-color-1: #111111;");
  });
});

describe("renderTailwindTokens", () => {
  it("produces a requireable CommonJS theme fragment", () => {
    const src = renderTailwindTokens(tokens);
    expect(src.startsWith("// Generated by Vibeboard")).toBe(true);
    // 执行一遍确认是合法 CJS
    const mod = { exports: {} as { theme?: { extend?: Record<string, Record<string, string>> } } };
    new Function("module", "exports", src)(mod, mod.exports);
    expect(mod.exports.theme?.extend?.colors).toEqual({
      background: "#181820",
      ink: "#F0F0F5",
      "accent-asset-01": "#7C3AED",
      "accent-asset-01-2": "#6D28D9",
    });
    expect(mod.exports.theme?.extend?.fontSize).toEqual({ "1": "14px", "2": "32px" });
    expect(mod.exports.theme?.extend?.borderRadius).toEqual({ "1": "8px", "2": "16px" });
  });
});
