/**
 * 将 Vibeboard handoff tokens 转为 Design Tokens Community Group (DTCG) 草案格式
 */

export type HandoffTokensLike = {
  color?: string[];
  /** 有语义名 + 来源的色板；存在时优先于匿名 color[] */
  palette?: Array<{
    name: string;
    value: string;
    usage?: string;
    source?: string;
    share?: number;
  }>;
  fontSize?: number[];
  radius?: number[];
  moodKeywords?: string[];
  visualStyle?: string | null;
};

/** DTCG-ish JSON（$value / $type）便于 Token Studio / Style Dictionary 消费 */
export function toDtcgTokens(tokens: HandoffTokensLike): Record<string, unknown> {
  const color: Record<string, unknown> = {};
  if (tokens.palette?.length) {
    const seen = new Set<string>();
    for (const entry of tokens.palette) {
      let key = entry.name.replace(/[^a-zA-Z0-9_-]+/g, "-");
      let n = 2;
      while (seen.has(key)) key = `${entry.name}-${n++}`;
      seen.add(key);
      color[key] = {
        $type: "color",
        $value: entry.value,
        ...(entry.usage || entry.source
          ? {
              $description: [
                entry.usage,
                entry.source ? `source: ${entry.source}` : "",
              ]
                .filter(Boolean)
                .join(" · "),
            }
          : {}),
        ...(typeof entry.share === "number"
          ? { $extensions: { "vibeboard.share": entry.share } }
          : {}),
      };
    }
  } else {
    (tokens.color ?? []).forEach((value, i) => {
      color[`color-${i + 1}`] = {
        $type: "color",
        $value: value,
      };
    });
  }

  const fontSize: Record<string, unknown> = {};
  (tokens.fontSize ?? []).forEach((value, i) => {
    fontSize[`size-${i + 1}`] = {
      $type: "dimension",
      $value: `${value}px`,
    };
  });

  const radius: Record<string, unknown> = {};
  (tokens.radius ?? []).forEach((value, i) => {
    radius[`radius-${i + 1}`] = {
      $type: "dimension",
      $value: `${value}px`,
    };
  });

  return {
    $description:
      "Generated by Vibeboard handoff. DTCG-compatible subset.",
    meta: {
      visualStyle: tokens.visualStyle ?? null,
      moodKeywords: tokens.moodKeywords ?? [],
    },
    color,
    fontSize,
    radius,
  };
}
